#!/usr/bin/env python3
"""Build the front-coded dictionaries embedded in the Spectrum releases."""

from __future__ import annotations

import argparse
import json
import struct
from collections import Counter
from pathlib import Path

BLOCK_SIZE = 16
PHYSICAL_BANKS = (0, 1, 3, 4, 6)


def load_words(path: Path, required: int = 20_000) -> list[str]:
    words: list[str] = []
    seen: set[str] = set()

    for raw in path.read_text(encoding="ascii").splitlines():
        word = raw.strip()
        if not word or word.startswith("#"):
            continue
        if not (3 <= len(word) <= 15):
            raise ValueError(f"word outside 3..15 characters: {word!r}")
        if not word.isascii() or not word.isalpha() or not word.islower():
            raise ValueError(f"word is not lowercase ASCII: {word!r}")
        if word in seen:
            raise ValueError(f"duplicate word: {word!r}")
        seen.add(word)
        words.append(word)

    if len(words) < required:
        raise ValueError(f"need at least {required} words, got {len(words)}")
    return words


def pack_letters(letters: str) -> bytes:
    result = bytearray()
    accumulator = 0
    bits = 0

    for letter in letters:
        accumulator = (accumulator << 5) | (ord(letter) - ord("a") + 1)
        bits += 5
        while bits >= 8:
            bits -= 8
            result.append((accumulator >> bits) & 0xFF)
            accumulator &= (1 << bits) - 1
    if bits:
        result.append((accumulator << (8 - bits)) & 0xFF)
    return bytes(result)


def encode(words: list[str]) -> bytes:
    ordered = sorted(words)
    block_count = (len(ordered) + BLOCK_SIZE - 1) // BLOCK_SIZE
    header_size = 4 + 2 * block_count
    records = bytearray()
    offsets: list[int] = []
    previous = ""

    for index, word in enumerate(ordered):
        if index % BLOCK_SIZE == 0:
            previous = ""
            offsets.append(header_size + len(records))

        prefix = 0
        while (
            prefix < len(previous)
            and prefix < len(word)
            and previous[prefix] == word[prefix]
        ):
            prefix += 1
        suffix = word[prefix:]
        if prefix > 15 or not 1 <= len(suffix) <= 15:
            raise AssertionError((previous, word, prefix, suffix))

        records.append((prefix << 4) | len(suffix))
        records.extend(pack_letters(suffix))
        previous = word

    result = bytearray(struct.pack("<HH", len(ordered), block_count))
    result.extend(struct.pack(f"<{block_count}H", *offsets))
    result.extend(records)
    return bytes(result)


def unpack_letters(data: bytes, position: int, length: int) -> tuple[str, int]:
    letters: list[str] = []
    accumulator = 0
    bits = 0

    for _ in range(length):
        while bits < 5:
            accumulator = (accumulator << 8) | data[position]
            position += 1
            bits += 8
        bits -= 5
        value = (accumulator >> bits) & 31
        accumulator = accumulator & ((1 << bits) - 1) if bits else 0
        letters.append(chr(ord("a") + value - 1))
    return "".join(letters), position


def decode(blob: bytes, index: int) -> str:
    count, block_count = struct.unpack_from("<HH", blob)
    if not 0 <= index < count:
        raise IndexError(index)
    block, within = divmod(index, BLOCK_SIZE)
    if block >= block_count:
        raise AssertionError(block)
    position = struct.unpack_from("<H", blob, 4 + 2 * block)[0]
    word = ""

    for _ in range(within + 1):
        header = blob[position]
        position += 1
        prefix, suffix_length = header >> 4, header & 15
        suffix, position = unpack_letters(blob, position, suffix_length)
        word = word[:prefix] + suffix
    return word


def verify(blob: bytes, expected: list[str]) -> None:
    ordered = sorted(expected)
    decoded = [decode(blob, index) for index in range(len(ordered))]
    if decoded != ordered:
        for index, (actual, wanted) in enumerate(zip(decoded, ordered)):
            if actual != wanted:
                raise AssertionError(
                    f"dictionary mismatch at {index}: {actual!r} != {wanted!r}"
                )
        raise AssertionError("dictionary has a mismatched length")


def length_counts(words: list[str]) -> dict[str, int]:
    counts = Counter(map(len, words))
    return {str(length): counts[length] for length in range(3, 16)}


def write_header(
    path: Path,
    sizes: dict[str, int],
    words_48_count: int,
    words_128_count: int,
    bank_words: int,
) -> None:
    text = f"""/* Generated by tools/build_dictionary.py. */
#ifndef HANGMAN_DICTIONARY_META_H
#define HANGMAN_DICTIONARY_META_H

#define DICTIONARY_BLOCK_SIZE {BLOCK_SIZE}u
#define DICTIONARY_48_WORDS {words_48_count}u
#define DICTIONARY_48_BYTES {sizes['48']}u
#define DICTIONARY_128_WORDS {words_128_count}u
#define DICTIONARY_128_WORDS_PER_BANK {bank_words}u
#define DICTIONARY_128_BANKS {len(PHYSICAL_BANKS)}u

#endif
"""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="ascii")


def write_assembly(asm48: Path, asm128: Path, build_dir: Path) -> None:
    # Keep BINARY paths relative when the build directory is relative.  The
    # generated assembly is prepared on the Actions host and compiled inside
    # a container mounted at /src, so embedding the host's absolute checkout
    # path would make an otherwise reproducible build fail.
    dictionary48 = (build_dir / "dict48.bin").as_posix()
    asm48.parent.mkdir(parents=True, exist_ok=True)
    asm48.write_text(
        "SECTION RODATA\n\n"
        "PUBLIC _dictionary_blob\n\n"
        "_dictionary_blob:\n"
        f'    BINARY "{dictionary48}"\n',
        encoding="ascii",
    )

    bank_lines: list[str] = []
    for physical in PHYSICAL_BANKS:
        dictionary = (build_dir / f"dict128-bank{physical}.bin").as_posix()
        bank_lines.extend(
            (
                f"SECTION RODATA_{physical}",
                f"PUBLIC _dictionary_bank{physical}",
                f"_dictionary_bank{physical}:",
                f'    BINARY "{dictionary}"',
                "",
            )
        )
    asm128.parent.mkdir(parents=True, exist_ok=True)
    asm128.write_text("\n".join(bank_lines), encoding="ascii")


def build(
    words_path: Path,
    build_dir: Path,
    header_path: Path,
    *,
    language: str = "pl",
    words_48_count: int = 4_000,
    words_128_count: int = 20_000,
    max_48_bytes: int = 20_000,
    asm48: Path | None = None,
    asm128: Path | None = None,
) -> dict[str, object]:
    if words_48_count > words_128_count:
        raise ValueError("48K word count cannot exceed the 128K word count")
    if words_128_count % len(PHYSICAL_BANKS):
        raise ValueError(
            f"128K word count must divide into {len(PHYSICAL_BANKS)} banks"
        )

    bank_words_count = words_128_count // len(PHYSICAL_BANKS)
    all_words = load_words(words_path, words_128_count)
    words48 = all_words[:words_48_count]
    words128 = sorted(all_words[:words_128_count])
    build_dir.mkdir(parents=True, exist_ok=True)

    blob48 = encode(words48)
    verify(blob48, words48)
    (build_dir / "dict48.bin").write_bytes(blob48)

    bank_manifest: list[dict[str, object]] = []
    sizes = {"48": len(blob48)}
    for logical, physical in enumerate(PHYSICAL_BANKS):
        start = logical * bank_words_count
        bank_words = words128[start : start + bank_words_count]
        blob = encode(bank_words)
        verify(blob, bank_words)
        if len(blob) > 16_384:
            raise ValueError(f"dictionary bank {physical} is too large: {len(blob)}")
        output = build_dir / f"dict128-bank{physical}.bin"
        output.write_bytes(blob)
        sizes[f"bank{physical}"] = len(blob)
        bank_manifest.append(
            {
                "logical_bank": logical,
                "physical_bank": physical,
                "words": len(bank_words),
                "bytes": len(blob),
                "first": bank_words[0],
                "last": bank_words[-1],
            }
        )

    if len(blob48) > max_48_bytes:
        raise ValueError(
            f"48K dictionary exceeds its {max_48_bytes}-byte budget: {len(blob48)}"
        )

    write_header(
        header_path,
        sizes,
        words_48_count,
        words_128_count,
        bank_words_count,
    )
    if (asm48 is None) != (asm128 is None):
        raise ValueError("both asm48 and asm128 must be provided together")
    if asm48 is not None and asm128 is not None:
        write_assembly(asm48, asm128, build_dir)

    manifest: dict[str, object] = {
        "format": "FC5/16",
        "description": "16-word front-coded blocks; suffix letters packed at 5 bits",
        "language": language,
        "source_words": str(words_path),
        "source_count": len(all_words),
        "limits": {
            "zx48_max_bytes": max_48_bytes,
            "zx128_bank_max_bytes": 16_384,
        },
        "zx48": {
            "words": words_48_count,
            "bytes": len(blob48),
            "fits": len(blob48) <= max_48_bytes,
            "bytes_per_word": round(len(blob48) / words_48_count, 3),
            "lengths": length_counts(words48),
        },
        "zx128": {
            "words": words_128_count,
            "bytes": sum(int(bank["bytes"]) for bank in bank_manifest),
            "bytes_per_word": round(
                sum(int(bank["bytes"]) for bank in bank_manifest) / words_128_count,
                3,
            ),
            "fits": all(int(bank["bytes"]) <= 16_384 for bank in bank_manifest),
            "lengths": length_counts(words128),
            "banks": bank_manifest,
        },
    }
    (build_dir / "dictionary-manifest.json").write_text(
        json.dumps(manifest, ensure_ascii=True, indent=2) + "\n", encoding="ascii"
    )
    return manifest


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--words", type=Path, required=True)
    parser.add_argument("--build-dir", type=Path, required=True)
    parser.add_argument("--header", type=Path, required=True)
    parser.add_argument("--language", default="pl")
    parser.add_argument("--words-48", type=int, default=4_000)
    parser.add_argument("--words-128", type=int, default=20_000)
    parser.add_argument("--max-48-bytes", type=int, default=20_000)
    parser.add_argument("--asm48", type=Path)
    parser.add_argument("--asm128", type=Path)
    args = parser.parse_args()

    manifest = build(
        args.words,
        args.build_dir,
        args.header,
        language=args.language,
        words_48_count=args.words_48,
        words_128_count=args.words_128,
        max_48_bytes=args.max_48_bytes,
        asm48=args.asm48,
        asm128=args.asm128,
    )
    print(
        f"48K: {manifest['zx48']['words']} words / {manifest['zx48']['bytes']} bytes"
    )
    print(
        f"128K: {manifest['zx128']['words']} words / "
        f"{manifest['zx128']['bytes']} bytes in {len(PHYSICAL_BANKS)} banks"
    )


if __name__ == "__main__":
    main()
